//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonMapEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonMapEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _004charmander {
            get {
                object obj = ResourceManager.GetObject("004charmander", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Data&gt;
        ///	&lt;RecoveryList Completed=&quot;true&quot; &gt;
        ///		&lt;inventoryItem ID=&quot;H001&quot; Name=&quot;Potion &quot; Type=&quot;1&quot; &gt;Recovers 20 HP &lt;/inventoryItem&gt;
        ///		&lt;inventoryItem ID=&quot;H002&quot; Name=&quot;Super Potion &quot; Type=&quot;1&quot; &gt;Recovers 50 HP &lt;/inventoryItem&gt;
        ///		&lt;inventoryItem ID=&quot;H003&quot; Name=&quot;Hyper Potion &quot; Type=&quot;1&quot; &gt;Recovers 200 HP &lt;/inventoryItem&gt;
        ///		&lt;inventoryItem ID=&quot;H004&quot; Name=&quot;Max Potion &quot; Type=&quot;1&quot; &gt;Recovers All HP &lt;/inventoryItem&gt;
        ///		&lt;inventoryItem ID=&quot;H005&quot; Name=&quot;Full Restore &quot; Type=&quot;1&quot; &gt;Fully Recovers HP and Status C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ItemList {
            get {
                return ResourceManager.GetString("ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Data&gt;
        ///	&lt;Moves&gt;
        ///		&lt;Move ID=&quot;1&quot; Name=&quot;Pound&quot; Type=&quot;Normal&quot; Category=&quot;Physical&quot; Contest=&quot;Tough&quot; PP=&quot;35&quot; Power=&quot;40&quot; Accuracy=&quot;1&quot; Gen=&quot;I&quot; /&gt;
        ///		&lt;Move ID=&quot;2&quot; Name=&quot;Karate Chop&quot; Type=&quot;Fighting&quot; Category=&quot;Physical&quot; Contest=&quot;Tough&quot; PP=&quot;25&quot; Power=&quot;50&quot; Accuracy=&quot;1&quot; Gen=&quot;I&quot; /&gt;
        ///		&lt;Move ID=&quot;3&quot; Name=&quot;DoubleSlap&quot; Type=&quot;Normal&quot; Category=&quot;Physical&quot; Contest=&quot;Tough&quot; PP=&quot;10&quot; Power=&quot;15&quot; Accuracy=&quot;0.85&quot; Gen=&quot;I&quot; /&gt;
        ///		&lt;Move ID=&quot;4&quot; Name=&quot;Comet Punch&quot; Type=&quot;Normal&quot; Category=&quot;Physical&quot; Contest=&quot;Tough&quot; PP=&quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MoveList {
            get {
                return ResourceManager.GetString("MoveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap N {
            get {
                object obj = ResourceManager.GetObject("N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Stamps&gt;
        ///	&lt;Object Name=&quot;Grass&quot;&gt;
        ///		&lt;Attribute name=&quot;Type&quot; Value=&quot;1&quot;/&gt;
        ///		&lt;Attribute name=&quot;Name&quot; Value=&quot;Grass&quot;/&gt;
        ///	&lt;/Object&gt;
        ///	&lt;Object Name=&quot;Tree&quot;&gt;
        ///		&lt;Attribute name=&quot;Type&quot; Value=&quot;3&quot;/&gt;
        ///		&lt;Attribute name=&quot;Name&quot; Value=&quot;Tree&quot;/&gt;
        ///		&lt;Attribute name=&quot;xStart&quot; value=&quot;0&quot;/&gt;
        ///		&lt;Attribute name=&quot;yStart&quot; value=&quot;6&quot;/&gt;
        ///		&lt;Attribute name=&quot;Terrain&quot; Value=&quot;2&quot;/&gt;
        ///	&lt;/Object&gt;
        ///	&lt;Object Name=&quot;Trainer&quot;&gt;
        ///		&lt;Attribute name=&quot;Type&quot; Value=&quot;6&quot;/&gt;
        ///		&lt;Attribute name=&quot;Name&quot; Value=&quot;Trainer&quot;/&gt;
        ///		&lt;Attribute name=&quot;T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Stamps {
            get {
                return ResourceManager.GetString("Stamps", resourceCulture);
            }
        }
    }
}
